#############################################################################
# Makefile for building: WiFiDetector
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  WiFiDetector.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile WiFiDetector.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude/opencv4 -Iinclude -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = WiFiDetector1.0.0
DISTDIR = /home/madius/lab_graf/.tmp/WiFiDetector1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,../WiFi_detector/lib
LIBS          = $(SUBLIBS) -lpthread /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = accesspointsettings.cpp \
		addnewelementinscene.cpp \
		addnewmap.cpp \
		customscene.cpp \
		form_log.cpp \
		forminteractivemap.cpp \
		infowidgit.cpp \
		listelement.cpp \
		main.cpp \
		settingsarea.cpp \
		settingsperimetr.cpp \
		startsettingenter.cpp qrc_style.cpp \
		moc_accesspointsettings.cpp \
		moc_addnewelementinscene.cpp \
		moc_addnewmap.cpp \
		moc_customscene.cpp \
		moc_form_log.cpp \
		moc_forminteractivemap.cpp \
		moc_infowidgit.cpp \
		moc_listelement.cpp \
		moc_settingsarea.cpp \
		moc_settingsperimetr.cpp \
		moc_startsettingenter.cpp
OBJECTS       = accesspointsettings.o \
		addnewelementinscene.o \
		addnewmap.o \
		customscene.o \
		form_log.o \
		forminteractivemap.o \
		infowidgit.o \
		listelement.o \
		main.o \
		settingsarea.o \
		settingsperimetr.o \
		startsettingenter.o \
		qrc_style.o \
		moc_accesspointsettings.o \
		moc_addnewelementinscene.o \
		moc_addnewmap.o \
		moc_customscene.o \
		moc_form_log.o \
		moc_forminteractivemap.o \
		moc_infowidgit.o \
		moc_listelement.o \
		moc_settingsarea.o \
		moc_settingsperimetr.o \
		moc_startsettingenter.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		WiFiDetector.pro accesspointsettings.h \
		addnewelementinscene.h \
		addnewmap.h \
		customscene.h \
		form_log.h \
		forminteractivemap.h \
		infowidgit.h \
		listelement.h \
		settingsarea.h \
		settingsperimetr.h \
		singleton.hpp \
		startsettingenter.h accesspointsettings.cpp \
		addnewelementinscene.cpp \
		addnewmap.cpp \
		customscene.cpp \
		form_log.cpp \
		forminteractivemap.cpp \
		infowidgit.cpp \
		listelement.cpp \
		main.cpp \
		settingsarea.cpp \
		settingsperimetr.cpp \
		startsettingenter.cpp
QMAKE_TARGET  = WiFiDetector
DESTDIR       = 
TARGET        = traveling_salesman


first: all
####### Build rules

WiFiDetector: ui_accesspointsettings.h ui_addnewelementinscene.h ui_addnewmap.h ui_form_log.h ui_forminteractivemap.h ui_settingsarea.h ui_settingsperimetr.h ui_startsettingenter.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WiFiDetector.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		WiFiDetector.pro \
		dark/style.qrc
	$(QMAKE) -o Makefile WiFiDetector.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
WiFiDetector.pro:
dark/style.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile WiFiDetector.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile WiFiDetector

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dark/style.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents accesspointsettings.h addnewelementinscene.h addnewmap.h customscene.h form_log.h forminteractivemap.h infowidgit.h listelement.h settingsarea.h settingsperimetr.h singleton.hpp startsettingenter.h $(DISTDIR)/
	$(COPY_FILE) --parents accesspointsettings.cpp addnewelementinscene.cpp addnewmap.cpp customscene.cpp form_log.cpp forminteractivemap.cpp infowidgit.cpp listelement.cpp main.cpp settingsarea.cpp settingsperimetr.cpp startsettingenter.cpp $(DISTDIR)/
	$(COPY_FILE) --parents accesspointsettings.ui addnewelementinscene.ui addnewmap.ui form_log.ui forminteractivemap.ui settingsarea.ui settingsperimetr.ui startsettingenter.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_style.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp
qrc_style.cpp: dark/style.qrc \
		/usr/lib/qt5/bin/rcc \
		dark/rc/transparent.png \
		dark/rc/sensor.png \
		dark/rc/line_horizontal_pressed.png \
		dark/rc/line_horizontal.png \
		dark/rc/arrow_left_disabled@2x.png \
		dark/rc/branch_more_focus.png \
		dark/rc/copy_.png \
		dark/rc/.keep \
		dark/rc/scale.png \
		dark/rc/arrow_down_disabled@2x.png \
		dark/rc/toolbar_move_vertical_pressed.png \
		dark/rc/cam_r.png \
		dark/rc/window_close_pressed@2x.png \
		dark/rc/arrow_up_focus.png \
		dark/rc/toolbar_separator_horizontal_pressed@2x.png \
		dark/rc/window_close_pressed.png \
		dark/rc/branch_open_disabled@2x.png \
		dark/rc/line_horizontal_focus@2x.png \
		dark/rc/checkbox_unchecked.png \
		dark/rc/radio_checked_focus@2x.png \
		dark/rc/checkbox_checked_pressed@2x.png \
		dark/rc/base_icon_disabled.png \
		dark/rc/toolbar_move_horizontal.png \
		dark/rc/window_close_disabled.png \
		dark/rc/branch_line@2x.png \
		dark/rc/toolbar_move_vertical@2x.png \
		dark/rc/arrow_right_pressed@2x.png \
		dark/rc/arrow_up_disabled.png \
		dark/rc/checkbox_checked@2x.png \
		dark/rc/toolbar_move_vertical_focus.png \
		dark/rc/radio_unchecked_disabled.png \
		dark/rc/checkbox_indeterminate.png \
		dark/rc/sensor_g.png \
		dark/rc/window_close_disabled@2x.png \
		dark/rc/window_grip_pressed@2x.png \
		dark/rc/none.png \
		dark/rc/?.png \
		dark/rc/door_g.png \
		dark/rc/toolbar_separator_horizontal_focus@2x.png \
		dark/rc/branch_closed_disabled.png \
		dark/rc/branch_line.png \
		dark/rc/checkbox_indeterminate_pressed.png \
		dark/rc/transparent_focus.png \
		dark/rc/toolbar_separator_horizontal.png \
		dark/rc/load.png \
		dark/rc/icon.jpg \
		dark/rc/branch_end_focus.png \
		dark/rc/checkbox_unchecked@2x.png \
		dark/rc/window_undock_disabled.png \
		dark/rc/radio_checked_pressed@2x.png \
		dark/rc/branch_end_focus@2x.png \
		dark/rc/toolbar_move_horizontal_focus.png \
		dark/rc/arrow_left_focus.png \
		dark/rc/arrow_left@2x.png \
		dark/rc/toolbar_separator_vertical_focus@2x.png \
		dark/rc/window_grip_focus@2x.png \
		dark/rc/window_undock_focus.png \
		dark/rc/tur_g.png \
		dark/rc/sensor_r.png \
		dark/rc/window_close.png \
		dark/rc/line_horizontal@2x.png \
		dark/rc/toolbar_move_vertical_disabled@2x.png \
		dark/rc/door_r.png \
		dark/rc/line_vertical_focus@2x.png \
		dark/rc/arrow_right@2x.png \
		dark/rc/base_icon_pressed.png \
		dark/rc/branch_line_focus.png \
		dark/rc/window_grip_focus.png \
		dark/rc/arrow_right_disabled@2x.png \
		dark/rc/branch_more_pressed@2x.png \
		dark/rc/toolbar_move_vertical_disabled.png \
		dark/rc/input.png \
		dark/rc/arrow_up.png \
		dark/rc/arrow_left_pressed@2x.png \
		dark/rc/checkbox_checked.png \
		dark/rc/toolbar_move_horizontal_disabled.png \
		dark/rc/line_vertical_pressed.png \
		dark/rc/base_icon_pressed@2x.png \
		dark/rc/toolbar_separator_vertical_focus.png \
		dark/rc/branch_end_pressed.png \
		dark/rc/checkbox_indeterminate_focus@2x.png \
		dark/rc/window_minimize_disabled.png \
		dark/rc/window_undock_pressed.png \
		dark/rc/radio_checked@2x.png \
		dark/rc/toolbar_move_horizontal_disabled@2x.png \
		dark/rc/branch_closed_disabled@2x.png \
		dark/rc/line_vertical.png \
		dark/rc/branch_line_disabled.png \
		dark/rc/tur_r.png \
		dark/rc/tresh.png \
		dark/rc/toolbar_separator_vertical.png \
		dark/rc/branch_more_disabled.png \
		dark/rc/toolbar_move_horizontal@2x.png \
		dark/rc/window_undock_disabled@2x.png \
		dark/rc/arrow_down_pressed.png \
		dark/rc/toolbar_separator_horizontal_disabled@2x.png \
		dark/rc/tur.png \
		dark/rc/cam.png \
		dark/rc/branch_more_disabled@2x.png \
		dark/rc/line_vertical_focus.png \
		dark/rc/toolbar_separator_horizontal@2x.png \
		dark/rc/arrow_left_focus@2x.png \
		dark/rc/transparent_focus@2x.png \
		dark/rc/branch_open_focus@2x.png \
		dark/rc/toolbar_separator_vertical_disabled@2x.png \
		dark/rc/arrow_down_focus@2x.png \
		dark/rc/arrow_up_pressed@2x.png \
		dark/rc/arrow_up_disabled@2x.png \
		dark/rc/checkbox_checked_disabled.png \
		dark/rc/checkbox_checked_disabled@2x.png \
		dark/rc/line_vertical@2x.png \
		dark/rc/window_close@2x.png \
		dark/rc/alarm.png \
		dark/rc/arrow_right_disabled.png \
		dark/rc/branch_open@2x.png \
		dark/rc/checkbox_unchecked_focus@2x.png \
		dark/rc/line_vertical_disabled@2x.png \
		dark/rc/branch_more.png \
		dark/rc/add_.png \
		dark/rc/transparent_pressed@2x.png \
		dark/rc/toolbar_move_vertical.png \
		dark/rc/line_horizontal_focus.png \
		dark/rc/window_minimize_focus.png \
		dark/rc/checkbox_indeterminate@2x.png \
		dark/rc/branch_end_pressed@2x.png \
		dark/rc/arrow_up_pressed.png \
		dark/rc/arrow_right.png \
		dark/rc/radio_checked_disabled@2x.png \
		dark/rc/branch_open_pressed.png \
		dark/rc/line_horizontal_disabled.png \
		dark/rc/window_close_focus.png \
		dark/rc/radio_checked_disabled.png \
		dark/rc/branch_more@2x.png \
		dark/rc/branch_open.png \
		dark/rc/checkbox_unchecked_disabled@2x.png \
		dark/rc/base_icon_focus@2x.png \
		dark/rc/checkbox_unchecked_pressed.png \
		dark/rc/window_close_focus@2x.png \
		dark/rc/window_minimize_pressed@2x.png \
		dark/rc/branch_closed.png \
		dark/rc/arrow_up_focus@2x.png \
		dark/rc/radio_checked_pressed.png \
		dark/rc/branch_end_disabled@2x.png \
		dark/rc/radio_unchecked_disabled@2x.png \
		dark/rc/radio_unchecked_focus@2x.png \
		dark/rc/base_icon@2x.png \
		dark/rc/toolbar_move_vertical_pressed@2x.png \
		dark/rc/toolbar_separator_vertical_pressed.png \
		dark/rc/toolbar_separator_horizontal_disabled.png \
		dark/rc/branch_line_disabled@2x.png \
		dark/rc/branch_closed_pressed.png \
		dark/rc/branch_closed_focus@2x.png \
		dark/rc/window_minimize@2x.png \
		dark/rc/window_minimize.png \
		dark/rc/transparent_pressed.png \
		dark/rc/window_grip@2x.png \
		dark/rc/checkbox_indeterminate_pressed@2x.png \
		dark/rc/base_icon_focus.png \
		dark/rc/checkbox_checked_pressed.png \
		dark/rc/arrow_down_focus.png \
		dark/rc/elevator.png \
		dark/rc/radio_checked.png \
		dark/rc/branch_end_disabled.png \
		dark/rc/toolbar_move_horizontal_pressed.png \
		dark/rc/radio_unchecked_focus.png \
		dark/rc/window_undock_focus@2x.png \
		dark/rc/radio_unchecked_pressed.png \
		dark/rc/toolbar_separator_vertical_disabled.png \
		dark/rc/window_undock.png \
		dark/rc/window_grip_disabled.png \
		dark/rc/branch_open_pressed@2x.png \
		dark/rc/radio_checked_focus.png \
		dark/rc/checkbox_checked_focus.png \
		dark/rc/window_undock_pressed@2x.png \
		dark/rc/move.png \
		dark/rc/line_vertical_disabled.png \
		dark/rc/checkbox_unchecked_focus.png \
		dark/rc/branch_closed_focus.png \
		dark/rc/no-signal.jpg \
		dark/rc/arrow_down@2x.png \
		dark/rc/toolbar_move_vertical_focus@2x.png \
		dark/rc/toolbar_separator_horizontal_focus.png \
		dark/rc/window_grip_disabled@2x.png \
		dark/rc/new_version.png \
		dark/rc/radio_unchecked.png \
		dark/rc/checkbox_unchecked_pressed@2x.png \
		dark/rc/window_grip.png \
		dark/rc/toolbar_separator_vertical@2x.png \
		dark/rc/arrow_right_focus.png \
		dark/rc/toolbar_move_horizontal_focus@2x.png \
		dark/rc/transparent_disabled@2x.png \
		dark/rc/base_icon_disabled@2x.png \
		dark/rc/window_grip_pressed.png \
		dark/rc/base_icon.png \
		dark/rc/transparent@2x.png \
		dark/rc/arrow_up@2x.png \
		dark/rc/line_vertical_pressed@2x.png \
		dark/rc/line_horizontal_disabled@2x.png \
		dark/rc/window_minimize_disabled@2x.png \
		dark/rc/checkbox_indeterminate_disabled.png \
		dark/rc/window_minimize_focus@2x.png \
		dark/rc/window_undock@2x.png \
		dark/rc/checkbox_indeterminate_disabled@2x.png \
		dark/rc/branch_line_pressed@2x.png \
		dark/rc/cam_g.png \
		dark/rc/branch_line_focus@2x.png \
		dark/rc/branch_line_pressed.png \
		dark/rc/window_minimize_pressed.png \
		dark/rc/radio_unchecked@2x.png \
		dark/rc/checkbox_indeterminate_focus.png \
		dark/rc/branch_closed_pressed@2x.png \
		dark/rc/arrow_left.png \
		dark/rc/toolbar_separator_vertical_pressed@2x.png \
		dark/rc/branch_more_focus@2x.png \
		dark/rc/alarm_empty.png \
		dark/rc/line_horizontal_pressed@2x.png \
		dark/rc/branch_more_pressed.png \
		dark/rc/arrow_right_pressed.png \
		dark/rc/arrow_down_pressed@2x.png \
		dark/rc/build.png \
		dark/rc/toolbar_separator_horizontal_pressed.png \
		dark/rc/branch_closed@2x.png \
		dark/rc/branch_end@2x.png \
		dark/rc/arrow_left_disabled.png \
		dark/rc/transparent_disabled.png \
		dark/rc/branch_open_disabled.png \
		dark/rc/branch_open_focus.png \
		dark/rc/arrow_down_disabled.png \
		dark/rc/radio_unchecked_pressed@2x.png \
		dark/rc/branch_end.png \
		dark/rc/door.png \
		dark/rc/checkbox_unchecked_disabled.png \
		dark/rc/checkbox_checked_focus@2x.png \
		dark/rc/arrow_left_pressed.png \
		dark/rc/arrow_down.png \
		dark/rc/toolbar_move_horizontal_pressed@2x.png \
		dark/rc/arrow_right_focus@2x.png \
		dark/style.qss \
		dark/rc/input.png
	/usr/lib/qt5/bin/rcc -name style dark/style.qrc -o qrc_style.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++1z -D_REENTRANT -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_accesspointsettings.cpp moc_addnewelementinscene.cpp moc_addnewmap.cpp moc_customscene.cpp moc_form_log.cpp moc_forminteractivemap.cpp moc_infowidgit.cpp moc_listelement.cpp moc_settingsarea.cpp moc_settingsperimetr.cpp moc_startsettingenter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_accesspointsettings.cpp moc_addnewelementinscene.cpp moc_addnewmap.cpp moc_customscene.cpp moc_form_log.cpp moc_forminteractivemap.cpp moc_infowidgit.cpp moc_listelement.cpp moc_settingsarea.cpp moc_settingsperimetr.cpp moc_startsettingenter.cpp
moc_accesspointsettings.cpp: accesspointsettings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include accesspointsettings.h -o moc_accesspointsettings.cpp

moc_addnewelementinscene.cpp: addnewelementinscene.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include addnewelementinscene.h -o moc_addnewelementinscene.cpp

moc_addnewmap.cpp: addnewmap.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include addnewmap.h -o moc_addnewmap.cpp

moc_customscene.cpp: customscene.h \
		addnewelementinscene.h \
		form_log.h \
		listelement.h \
		infowidgit.h \
		settingsarea.h \
		settingsperimetr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include customscene.h -o moc_customscene.cpp

moc_form_log.cpp: form_log.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include form_log.h -o moc_form_log.cpp

moc_forminteractivemap.cpp: forminteractivemap.h \
		addnewmap.h \
		customscene.h \
		addnewelementinscene.h \
		form_log.h \
		listelement.h \
		infowidgit.h \
		settingsarea.h \
		settingsperimetr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include forminteractivemap.h -o moc_forminteractivemap.cpp

moc_infowidgit.cpp: infowidgit.h \
		form_log.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include infowidgit.h -o moc_infowidgit.cpp

moc_listelement.cpp: listelement.h \
		infowidgit.h \
		form_log.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include listelement.h -o moc_listelement.cpp

moc_settingsarea.cpp: settingsarea.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include settingsarea.h -o moc_settingsarea.cpp

moc_settingsperimetr.cpp: settingsperimetr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include settingsperimetr.h -o moc_settingsperimetr.cpp

moc_startsettingenter.cpp: startsettingenter.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/madius/lab_graf/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/madius/lab_graf -I/home/madius/lab_graf/include/opencv4 -I/home/madius/lab_graf/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include startsettingenter.h -o moc_startsettingenter.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_accesspointsettings.h ui_addnewelementinscene.h ui_addnewmap.h ui_form_log.h ui_forminteractivemap.h ui_settingsarea.h ui_settingsperimetr.h ui_startsettingenter.h
compiler_uic_clean:
	-$(DEL_FILE) ui_accesspointsettings.h ui_addnewelementinscene.h ui_addnewmap.h ui_form_log.h ui_forminteractivemap.h ui_settingsarea.h ui_settingsperimetr.h ui_startsettingenter.h
ui_accesspointsettings.h: accesspointsettings.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic accesspointsettings.ui -o ui_accesspointsettings.h

ui_addnewelementinscene.h: addnewelementinscene.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic addnewelementinscene.ui -o ui_addnewelementinscene.h

ui_addnewmap.h: addnewmap.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic addnewmap.ui -o ui_addnewmap.h

ui_form_log.h: form_log.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic form_log.ui -o ui_form_log.h

ui_forminteractivemap.h: forminteractivemap.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic forminteractivemap.ui -o ui_forminteractivemap.h

ui_settingsarea.h: settingsarea.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic settingsarea.ui -o ui_settingsarea.h

ui_settingsperimetr.h: settingsperimetr.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic settingsperimetr.ui -o ui_settingsperimetr.h

ui_startsettingenter.h: startsettingenter.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic startsettingenter.ui -o ui_startsettingenter.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

accesspointsettings.o: accesspointsettings.cpp accesspointsettings.h \
		ui_accesspointsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accesspointsettings.o accesspointsettings.cpp

addnewelementinscene.o: addnewelementinscene.cpp addnewelementinscene.h \
		ui_addnewelementinscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addnewelementinscene.o addnewelementinscene.cpp

addnewmap.o: addnewmap.cpp addnewmap.h \
		ui_addnewmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addnewmap.o addnewmap.cpp

customscene.o: customscene.cpp customscene.h \
		addnewelementinscene.h \
		form_log.h \
		listelement.h \
		infowidgit.h \
		settingsarea.h \
		settingsperimetr.h \
		forminteractivemap.h \
		addnewmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customscene.o customscene.cpp

form_log.o: form_log.cpp form_log.h \
		ui_form_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form_log.o form_log.cpp

forminteractivemap.o: forminteractivemap.cpp forminteractivemap.h \
		addnewmap.h \
		customscene.h \
		addnewelementinscene.h \
		form_log.h \
		listelement.h \
		infowidgit.h \
		settingsarea.h \
		settingsperimetr.h \
		ui_forminteractivemap.h \
		accesspointsettings.h \
		include/opencv4/opencv2/imgproc.hpp \
		include/opencv4/opencv2/core.hpp \
		include/opencv4/opencv2/core/cvdef.h \
		include/opencv4/opencv2/core/version.hpp \
		include/opencv4/opencv2/core/hal/interface.h \
		include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		include/opencv4/opencv2/core/cv_cpu_helper.h \
		include/opencv4/opencv2/core/hal/msa_macros.h \
		include/opencv4/opencv2/core/fast_math.hpp \
		include/opencv4/opencv2/core/base.hpp \
		include/opencv4/opencv2/opencv_modules.hpp \
		include/opencv4/opencv2/core/cvstd.hpp \
		include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		include/opencv4/opencv2/core/neon_utils.hpp \
		include/opencv4/opencv2/core/vsx_utils.hpp \
		include/opencv4/opencv2/core/check.hpp \
		include/opencv4/opencv2/core/traits.hpp \
		include/opencv4/opencv2/core/matx.hpp \
		include/opencv4/opencv2/core/saturate.hpp \
		include/opencv4/opencv2/core/types.hpp \
		include/opencv4/opencv2/core/mat.hpp \
		include/opencv4/opencv2/core/bufferpool.hpp \
		include/opencv4/opencv2/core/mat.inl.hpp \
		include/opencv4/opencv2/core/persistence.hpp \
		include/opencv4/opencv2/core/operations.hpp \
		include/opencv4/opencv2/core/cvstd.inl.hpp \
		include/opencv4/opencv2/core/utility.hpp \
		include/opencv4/opencv2/core/utils/instrumentation.hpp \
		include/opencv4/opencv2/core/utils/tls.hpp \
		include/opencv4/opencv2/core/optim.hpp \
		include/opencv4/opencv2/core/ovx.hpp \
		include/opencv4/opencv2/imgproc/segmentation.hpp \
		startsettingenter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forminteractivemap.o forminteractivemap.cpp

infowidgit.o: infowidgit.cpp infowidgit.h \
		form_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infowidgit.o infowidgit.cpp

listelement.o: listelement.cpp listelement.h \
		infowidgit.h \
		form_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listelement.o listelement.cpp

main.o: main.cpp include/boost/stacktrace.hpp \
		include/boost/config.hpp \
		include/boost/config/user.hpp \
		include/boost/config/detail/select_compiler_config.hpp \
		include/boost/config/compiler/nvcc.hpp \
		include/boost/config/compiler/gcc_xml.hpp \
		include/boost/config/compiler/cray.hpp \
		include/boost/config/compiler/common_edg.hpp \
		include/boost/config/compiler/comeau.hpp \
		include/boost/config/compiler/pathscale.hpp \
		include/boost/config/compiler/clang.hpp \
		include/boost/config/compiler/clang_version.hpp \
		include/boost/config/compiler/intel.hpp \
		include/boost/config/compiler/visualc.hpp \
		include/boost/config/pragma_message.hpp \
		include/boost/config/helper_macros.hpp \
		include/boost/config/compiler/gcc.hpp \
		include/boost/config/compiler/digitalmars.hpp \
		include/boost/config/compiler/kai.hpp \
		include/boost/config/compiler/sgi_mipspro.hpp \
		include/boost/config/compiler/compaq_cxx.hpp \
		include/boost/config/compiler/greenhills.hpp \
		include/boost/config/compiler/codegear.hpp \
		include/boost/config/compiler/borland.hpp \
		include/boost/config/compiler/metrowerks.hpp \
		include/boost/config/compiler/sunpro_cc.hpp \
		include/boost/config/compiler/hp_acc.hpp \
		include/boost/config/compiler/mpw.hpp \
		include/boost/config/compiler/xlcpp_zos.hpp \
		include/boost/config/compiler/xlcpp.hpp \
		include/boost/config/compiler/vacpp.hpp \
		include/boost/config/compiler/pgi.hpp \
		include/boost/config/detail/select_stdlib_config.hpp \
		include/boost/config/stdlib/stlport.hpp \
		include/boost/config/stdlib/libcomo.hpp \
		include/boost/config/no_tr1/utility.hpp \
		include/boost/config/stdlib/roguewave.hpp \
		include/boost/config/stdlib/libcpp.hpp \
		include/boost/config/stdlib/libstdcpp3.hpp \
		include/boost/config/stdlib/sgi.hpp \
		include/boost/config/stdlib/msl.hpp \
		include/boost/config/detail/posix_features.hpp \
		include/boost/config/stdlib/xlcpp_zos.hpp \
		include/boost/config/stdlib/vacpp.hpp \
		include/boost/config/stdlib/modena.hpp \
		include/boost/config/stdlib/dinkumware.hpp \
		include/boost/config/detail/select_platform_config.hpp \
		include/boost/config/platform/linux.hpp \
		include/boost/config/platform/bsd.hpp \
		include/boost/config/platform/solaris.hpp \
		include/boost/config/platform/irix.hpp \
		include/boost/config/platform/hpux.hpp \
		include/boost/config/platform/cygwin.hpp \
		include/boost/config/platform/win32.hpp \
		include/boost/config/platform/beos.hpp \
		include/boost/config/platform/macos.hpp \
		include/boost/config/platform/zos.hpp \
		include/boost/config/platform/aix.hpp \
		include/boost/config/platform/amigaos.hpp \
		include/boost/config/platform/qnxnto.hpp \
		include/boost/config/platform/vxworks.hpp \
		include/boost/config/platform/symbian.hpp \
		include/boost/config/platform/cray.hpp \
		include/boost/config/platform/vms.hpp \
		include/boost/config/detail/suffix.hpp \
		include/boost/config/detail/cxx_composite.hpp \
		include/boost/stacktrace/frame.hpp \
		include/boost/core/explicit_operator_bool.hpp \
		include/boost/config/workaround.hpp \
		include/boost/stacktrace/safe_dump_to.hpp \
		include/boost/winapi/config.hpp \
		include/boost/predef/version_number.h \
		include/boost/predef/platform.h \
		include/boost/predef/platform/android.h \
		include/boost/predef/make.h \
		include/boost/predef/detail/test.h \
		include/boost/predef/detail/platform_detected.h \
		include/boost/predef/platform/cloudabi.h \
		include/boost/predef/platform/mingw.h \
		include/boost/predef/platform/mingw32.h \
		include/boost/predef/platform/mingw64.h \
		include/boost/predef/platform/windows_uwp.h \
		include/boost/predef/os/windows.h \
		include/boost/predef/detail/os_detected.h \
		include/boost/predef/platform/windows_desktop.h \
		include/boost/predef/platform/windows_phone.h \
		include/boost/predef/platform/windows_server.h \
		include/boost/predef/platform/windows_store.h \
		include/boost/predef/platform/windows_system.h \
		include/boost/predef/platform/windows_runtime.h \
		include/boost/predef/platform/ios.h \
		include/boost/predef/os/ios.h \
		include/boost/stacktrace/detail/push_options.h \
		include/boost/stacktrace/detail/pop_options.h \
		include/boost/stacktrace/detail/safe_dump_noop.ipp \
		include/boost/stacktrace/detail/collect_noop.ipp \
		include/boost/stacktrace/detail/safe_dump_win.ipp \
		include/boost/core/noncopyable.hpp \
		include/boost/winapi/get_current_process.hpp \
		include/boost/winapi/basic_types.hpp \
		include/boost/winapi/detail/header.hpp \
		include/boost/winapi/detail/footer.hpp \
		include/boost/winapi/file_management.hpp \
		include/boost/winapi/limits.hpp \
		include/boost/winapi/time.hpp \
		include/boost/winapi/overlapped.hpp \
		include/boost/winapi/handles.hpp \
		include/boost/winapi/access_rights.hpp \
		include/boost/stacktrace/detail/safe_dump_posix.ipp \
		include/boost/stacktrace/detail/collect_msvc.ipp \
		include/boost/winapi/stack_backtrace.hpp \
		include/boost/stacktrace/detail/collect_unwind.ipp \
		include/boost/predef.h \
		include/boost/predef/language.h \
		include/boost/predef/language/stdc.h \
		include/boost/predef/language/stdcpp.h \
		include/boost/predef/language/objc.h \
		include/boost/predef/language/cuda.h \
		include/boost/predef/architecture.h \
		include/boost/predef/architecture/alpha.h \
		include/boost/predef/architecture/arm.h \
		include/boost/predef/architecture/blackfin.h \
		include/boost/predef/architecture/convex.h \
		include/boost/predef/architecture/e2k.h \
		include/boost/predef/architecture/ia64.h \
		include/boost/predef/architecture/loongarch.h \
		include/boost/predef/architecture/m68k.h \
		include/boost/predef/architecture/mips.h \
		include/boost/predef/architecture/parisc.h \
		include/boost/predef/architecture/ppc.h \
		include/boost/predef/architecture/ptx.h \
		include/boost/predef/architecture/pyramid.h \
		include/boost/predef/architecture/riscv.h \
		include/boost/predef/architecture/rs6k.h \
		include/boost/predef/architecture/sparc.h \
		include/boost/predef/architecture/superh.h \
		include/boost/predef/architecture/sys370.h \
		include/boost/predef/architecture/sys390.h \
		include/boost/predef/architecture/x86.h \
		include/boost/predef/architecture/x86/32.h \
		include/boost/predef/architecture/x86/64.h \
		include/boost/predef/architecture/z.h \
		include/boost/predef/compiler.h \
		include/boost/predef/compiler/borland.h \
		include/boost/predef/detail/comp_detected.h \
		include/boost/predef/compiler/clang.h \
		include/boost/predef/compiler/comeau.h \
		include/boost/predef/compiler/compaq.h \
		include/boost/predef/compiler/diab.h \
		include/boost/predef/compiler/digitalmars.h \
		include/boost/predef/compiler/dignus.h \
		include/boost/predef/compiler/edg.h \
		include/boost/predef/compiler/ekopath.h \
		include/boost/predef/compiler/gcc_xml.h \
		include/boost/predef/compiler/gcc.h \
		include/boost/predef/compiler/greenhills.h \
		include/boost/predef/compiler/hp_acc.h \
		include/boost/predef/compiler/iar.h \
		include/boost/predef/compiler/ibm.h \
		include/boost/predef/compiler/intel.h \
		include/boost/predef/compiler/kai.h \
		include/boost/predef/compiler/llvm.h \
		include/boost/predef/compiler/metaware.h \
		include/boost/predef/compiler/metrowerks.h \
		include/boost/predef/compiler/microtec.h \
		include/boost/predef/compiler/mpw.h \
		include/boost/predef/compiler/nvcc.h \
		include/boost/predef/compiler/palm.h \
		include/boost/predef/compiler/pgi.h \
		include/boost/predef/compiler/sgi_mipspro.h \
		include/boost/predef/compiler/sunpro.h \
		include/boost/predef/compiler/tendra.h \
		include/boost/predef/compiler/visualc.h \
		include/boost/predef/compiler/watcom.h \
		include/boost/predef/library.h \
		include/boost/predef/library/c.h \
		include/boost/predef/library/c/_prefix.h \
		include/boost/predef/detail/_cassert.h \
		include/boost/predef/library/c/cloudabi.h \
		include/boost/predef/library/c/gnu.h \
		include/boost/predef/library/c/uc.h \
		include/boost/predef/library/c/vms.h \
		include/boost/predef/library/c/zos.h \
		include/boost/predef/library/std.h \
		include/boost/predef/library/std/_prefix.h \
		include/boost/predef/detail/_exception.h \
		include/boost/predef/library/std/cxx.h \
		include/boost/predef/library/std/dinkumware.h \
		include/boost/predef/library/std/libcomo.h \
		include/boost/predef/library/std/modena.h \
		include/boost/predef/library/std/msl.h \
		include/boost/predef/library/std/roguewave.h \
		include/boost/predef/library/std/sgi.h \
		include/boost/predef/library/std/stdcpp3.h \
		include/boost/predef/library/std/stlport.h \
		include/boost/predef/library/std/vacpp.h \
		include/boost/predef/os.h \
		include/boost/predef/os/aix.h \
		include/boost/predef/os/amigaos.h \
		include/boost/predef/os/beos.h \
		include/boost/predef/os/bsd.h \
		include/boost/predef/os/macos.h \
		include/boost/predef/os/bsd/bsdi.h \
		include/boost/predef/os/bsd/dragonfly.h \
		include/boost/predef/os/bsd/free.h \
		include/boost/predef/os/bsd/open.h \
		include/boost/predef/os/bsd/net.h \
		include/boost/predef/os/cygwin.h \
		include/boost/predef/os/haiku.h \
		include/boost/predef/os/hpux.h \
		include/boost/predef/os/irix.h \
		include/boost/predef/os/linux.h \
		include/boost/predef/os/os400.h \
		include/boost/predef/os/qnxnto.h \
		include/boost/predef/os/solaris.h \
		include/boost/predef/os/unix.h \
		include/boost/predef/os/vms.h \
		include/boost/predef/other.h \
		include/boost/predef/other/endian.h \
		include/boost/predef/other/wordsize.h \
		include/boost/predef/other/workaround.h \
		include/boost/predef/hardware.h \
		include/boost/predef/hardware/simd.h \
		include/boost/predef/hardware/simd/x86.h \
		include/boost/predef/hardware/simd/x86/versions.h \
		include/boost/predef/hardware/simd/x86_amd.h \
		include/boost/predef/hardware/simd/x86_amd/versions.h \
		include/boost/predef/hardware/simd/arm.h \
		include/boost/predef/hardware/simd/arm/versions.h \
		include/boost/predef/hardware/simd/ppc.h \
		include/boost/predef/hardware/simd/ppc/versions.h \
		include/boost/predef/version.h \
		include/boost/stacktrace/detail/frame_decl.hpp \
		include/boost/stacktrace/detail/void_ptr_cast.hpp \
		include/boost/static_assert.hpp \
		include/boost/detail/workaround.hpp \
		include/boost/type_traits/is_pointer.hpp \
		include/boost/type_traits/integral_constant.hpp \
		include/boost/stacktrace/detail/frame_noop.ipp \
		include/boost/stacktrace/detail/frame_msvc.ipp \
		include/boost/core/demangle.hpp \
		include/boost/stacktrace/detail/to_dec_array.hpp \
		include/boost/array.hpp \
		include/boost/assert.hpp \
		include/boost/current_function.hpp \
		include/boost/swap.hpp \
		include/boost/core/swap.hpp \
		include/boost/core/enable_if.hpp \
		include/boost/throw_exception.hpp \
		include/boost/exception/exception.hpp \
		include/boost/assert/source_location.hpp \
		include/boost/cstdint.hpp \
		include/boost/limits.hpp \
		include/boost/stacktrace/detail/to_hex_array.hpp \
		include/boost/type_traits/make_unsigned.hpp \
		include/boost/type_traits/conditional.hpp \
		include/boost/type_traits/is_integral.hpp \
		include/boost/type_traits/is_signed.hpp \
		include/boost/type_traits/remove_cv.hpp \
		include/boost/type_traits/is_enum.hpp \
		include/boost/type_traits/intrinsics.hpp \
		include/boost/type_traits/detail/config.hpp \
		include/boost/version.hpp \
		include/boost/type_traits/is_same.hpp \
		include/boost/type_traits/is_reference.hpp \
		include/boost/type_traits/is_lvalue_reference.hpp \
		include/boost/type_traits/is_rvalue_reference.hpp \
		include/boost/type_traits/detail/is_rvalue_reference_msvc10_fix.hpp \
		include/boost/type_traits/is_volatile.hpp \
		include/boost/type_traits/is_void.hpp \
		include/boost/type_traits/add_reference.hpp \
		include/boost/type_traits/is_arithmetic.hpp \
		include/boost/type_traits/is_floating_point.hpp \
		include/boost/type_traits/is_convertible.hpp \
		include/boost/type_traits/is_complete.hpp \
		include/boost/type_traits/declval.hpp \
		include/boost/type_traits/add_rvalue_reference.hpp \
		include/boost/type_traits/remove_reference.hpp \
		include/boost/type_traits/is_function.hpp \
		include/boost/type_traits/detail/is_function_cxx_11.hpp \
		include/boost/type_traits/detail/is_function_cxx_03.hpp \
		include/boost/type_traits/detail/is_function_ptr_helper.hpp \
		include/boost/type_traits/detail/is_function_ptr_tester.hpp \
		include/boost/type_traits/detail/yes_no_type.hpp \
		include/boost/type_traits/detail/is_function_msvc10_fix.hpp \
		include/boost/type_traits/is_array.hpp \
		include/boost/type_traits/is_abstract.hpp \
		include/boost/type_traits/is_class.hpp \
		include/boost/type_traits/is_union.hpp \
		include/boost/type_traits/is_scalar.hpp \
		include/boost/type_traits/is_member_pointer.hpp \
		include/boost/type_traits/is_member_function_pointer.hpp \
		include/boost/type_traits/detail/is_member_function_pointer_cxx_11.hpp \
		include/boost/type_traits/detail/is_member_function_pointer_cxx_03.hpp \
		include/boost/type_traits/detail/is_mem_fun_pointer_impl.hpp \
		include/boost/type_traits/detail/is_mem_fun_pointer_tester.hpp \
		include/boost/type_traits/is_polymorphic.hpp \
		include/boost/type_traits/add_lvalue_reference.hpp \
		include/boost/type_traits/is_unsigned.hpp \
		include/boost/type_traits/is_const.hpp \
		include/boost/type_traits/add_const.hpp \
		include/boost/type_traits/add_volatile.hpp \
		include/boost/stacktrace/detail/frame_unwind.ipp \
		include/boost/stacktrace/detail/location_from_symbol.hpp \
		include/boost/winapi/dll.hpp \
		include/boost/winapi/get_proc_address.hpp \
		include/boost/stacktrace/detail/libbacktrace_impls.hpp \
		include/boost/stacktrace/detail/addr2line_impls.hpp \
		include/boost/stacktrace/detail/try_dec_convert.hpp \
		include/boost/stacktrace/detail/unwind_base_impls.hpp \
		include/boost/stacktrace/stacktrace.hpp \
		include/boost/core/no_exceptions_support.hpp \
		include/boost/container_hash/hash_fwd.hpp \
		include/boost/stacktrace/stacktrace_fwd.hpp \
		forminteractivemap.h \
		addnewmap.h \
		customscene.h \
		addnewelementinscene.h \
		form_log.h \
		listelement.h \
		infowidgit.h \
		settingsarea.h \
		settingsperimetr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

settingsarea.o: settingsarea.cpp settingsarea.h \
		ui_settingsarea.h \
		listelement.h \
		infowidgit.h \
		form_log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsarea.o settingsarea.cpp

settingsperimetr.o: settingsperimetr.cpp settingsperimetr.h \
		ui_settingsperimetr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsperimetr.o settingsperimetr.cpp

startsettingenter.o: startsettingenter.cpp startsettingenter.h \
		ui_startsettingenter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startsettingenter.o startsettingenter.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

moc_accesspointsettings.o: moc_accesspointsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accesspointsettings.o moc_accesspointsettings.cpp

moc_addnewelementinscene.o: moc_addnewelementinscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addnewelementinscene.o moc_addnewelementinscene.cpp

moc_addnewmap.o: moc_addnewmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addnewmap.o moc_addnewmap.cpp

moc_customscene.o: moc_customscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customscene.o moc_customscene.cpp

moc_form_log.o: moc_form_log.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form_log.o moc_form_log.cpp

moc_forminteractivemap.o: moc_forminteractivemap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_forminteractivemap.o moc_forminteractivemap.cpp

moc_infowidgit.o: moc_infowidgit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infowidgit.o moc_infowidgit.cpp

moc_listelement.o: moc_listelement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_listelement.o moc_listelement.cpp

moc_settingsarea.o: moc_settingsarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsarea.o moc_settingsarea.cpp

moc_settingsperimetr.o: moc_settingsperimetr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsperimetr.o moc_settingsperimetr.cpp

moc_startsettingenter.o: moc_startsettingenter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startsettingenter.o moc_startsettingenter.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/WiFiDetector/bin || mkdir -p $(INSTALL_ROOT)/opt/WiFiDetector/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/WiFiDetector/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/WiFiDetector/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/WiFiDetector/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

